global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'java-app'
    static_configs:
      - targets: ['java-app:8080']
    metrics_path: '/actuator/prometheus'
    
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
